---
- name: Update code and run Python script in tmux
  hosts: all
  gather_facts: false
  tasks:
    - name: Close/terminate the application if running
      shell: |
        ps -ef | grep 'supernode_inference_layer' | grep -v grep | awk '{print $2}' | xargs -r kill -9
        ps -ef | grep 'swiss_army_llama' | grep -v grep | awk '{print $2}' | xargs -r kill -9
      ignore_errors: true

    - name: Update code
      shell: |
        git stash
        git pull
      args:
        chdir: ~/python_inference_layer_server

    - name: Get the name of the existing tmux session
      shell: tmux list-sessions -F '#{session_name}' | head -1
      register: tmux_session_name
      ignore_errors: true

    - name: Create tmux session if it doesn't exist
      shell: tmux new-session -d -s default_session
      when: tmux_session_name.stdout == ""

    - name: Set the tmux session name
      set_fact:
        session_name: "{{ tmux_session_name.stdout if tmux_session_name.stdout else 'default_session' }}"

    - name: Check if supernode_script window exists
      shell: tmux list-windows -t {{ session_name }} -F '#{window_name}' | grep -q '^supernode_script$'
      register: window_exists
      ignore_errors: true

    - name: Kill supernode_script window if it exists
      shell: tmux kill-window -t {{ session_name }}:supernode_script
      when: window_exists.rc == 0

    - name: Create temporary script
      copy:
        content: |
          #!/bin/bash
          cd ~/python_inference_layer_server
          . ~/.bashrc
          pyenv local 3.12
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install wheel           
          pip install -r requirements.txt
          python main.py
        dest: ~/run_script.sh
        mode: '0755'

    - name: Launch script in new tmux window
      shell: |
        tmux new-window -t {{ session_name }}: -n supernode_script -d "bash -c '~/run_script.sh'"
      register: script_output

    - name: Remove temporary script
      file:
        path: ~/run_script.sh
        state: absent
