---
- name: Update code and run Exo Python script in tmux
  hosts: all
  gather_facts: false
  become: true
  become_user: ubuntu
  tasks:
    - name: Determine the user shell
      shell: echo $SHELL
      register: user_shell
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Set shell path and profile file
      set_fact:
        shell_path: "{{ user_shell.stdout }}"
        profile_file: "{{ 'zshrc' if '/zsh' in user_shell.stdout else 'bashrc' }}"
      ignore_errors: yes

    - name: Check if exo_pastel directory exists
      stat:
        path: /home/ubuntu/exo_pastel
      register: exo_dir

    - name: Clone Exo repository if it doesn't exist
      shell: |
        git clone https://github.com/pastelnetwork/exo_pastel
      args:
        chdir: /home/ubuntu
        executable: "{{ shell_path }}"
      when: not exo_dir.stat.exists
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Change to exo_pastel directory and set Python version with pyenv
      shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        if command -v pyenv >/dev/null; then
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
        fi
        cd /home/ubuntu/exo_pastel
        pyenv local 3.12
      args:
        executable: "{{ shell_path }}"
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Pull latest code if exo_pastel directory exists
      shell: |
        git stash
        git pull
      args:
        chdir: /home/ubuntu/exo_pastel
        executable: "{{ shell_path }}"
      when: exo_dir.stat.exists
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Create temporary script for setting up and running Exo
      copy:
        content: |
          #!/bin/{{ 'zsh' if '/zsh' in shell_path else 'bash' }}
          source ~/.{{ profile_file }}
          cd /home/ubuntu/exo_pastel
          pyenv local 3.12
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install --upgrade setuptools wheel
          pip install .
          python main.py
        dest: /home/ubuntu/run_exo.sh
        mode: '0755'
      retries: 3
      delay: 60
      ignore_errors: yes

    - name: Get the name of the existing tmux session
      shell: tmux list-sessions -F '#{session_name}' | head -1
      register: tmux_session_name
      ignore_errors: yes
      async: 600
      poll: 10

    - name: Create tmux session if it doesn't exist
      shell: tmux new-session -d -s default_session
      when: tmux_session_name.stdout == ""
      args:
        executable: "{{ shell_path }}"
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Set the tmux session name
      set_fact:
        session_name: "{{ tmux_session_name.stdout if tmux_session_name.stdout else 'default_session' }}"
      ignore_errors: yes

    - name: Check if exo window exists
      shell: tmux list-windows -t {{ session_name }} -F '#{window_name}' | grep -q '^exo$'
      register: exo_window_exists
      ignore_errors: yes
      async: 600
      poll: 10

    - name: Kill exo window if it exists
      shell: tmux kill-window -t {{ session_name }}:exo
      when: exo_window_exists.rc == 0
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Launch Exo script in new tmux window
      shell: |
        tmux new-window -t {{ session_name }}: -n exo -d "{{ shell_path }} -c '/home/ubuntu/run_exo.sh'"
      args:
        executable: "{{ shell_path }}"
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Remove temporary script
      file:
        path: /home/ubuntu/run_exo.sh
        state: absent
      retries: 3
      delay: 60
      ignore_errors: yes
